"use client";

import { useControllableState } from "@radix-ui/react-use-controllable-state";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { cn } from "@/lib/utils";
import type { ComponentProps, ReactNode } from "react";
import {
  createContext,
  memo,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import { DotMatrixIcon } from "@/components/dotmatrix/icons";
import type { DotMatrixIconName } from "@/components/dotmatrix/icons";
import { Shimmer } from "./shimmer";

// ─── Context ──────────────────────────────────────────────────────────────────

interface ChainOfThoughtContextValue {
  isOpen: boolean;
  setIsOpen: (open: boolean) => void;
}

const ChainOfThoughtContext = createContext<ChainOfThoughtContextValue | null>(
  null,
);

const useChainOfThought = () => {
  const context = useContext(ChainOfThoughtContext);
  if (!context) {
    throw new Error(
      "ChainOfThought components must be used within ChainOfThought",
    );
  }
  return context;
};

// ─── Root ─────────────────────────────────────────────────────────────────────

export type ChainOfThoughtProps = ComponentProps<"div"> & {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  isStreaming?: boolean;
  /** Total steps count for the header badge */
  stepCount?: number;
};

export const ChainOfThought = memo(
  ({
    className,
    open,
    defaultOpen = false,
    onOpenChange,
    isStreaming = false,
    stepCount,
    children,
    ...props
  }: ChainOfThoughtProps) => {
    const [isOpen, setIsOpen] = useControllableState({
      defaultProp: defaultOpen,
      onChange: onOpenChange,
      prop: open,
    });

    const ctx = useMemo(
      () => ({ isOpen: isOpen ?? defaultOpen, setIsOpen }),
      [isOpen, setIsOpen, defaultOpen],
    );

    return (
      <ChainOfThoughtContext.Provider value={ctx}>
        <div className={cn("not-prose mb-2 w-full", className)} {...props}>
          {/* Header trigger */}
          <ChainOfThoughtHeader
            isStreaming={isStreaming}
            stepCount={stepCount}
          />
          {/* Steps body */}
          <ChainOfThoughtContent>{children}</ChainOfThoughtContent>
        </div>
      </ChainOfThoughtContext.Provider>
    );
  },
);

// ─── Header ───────────────────────────────────────────────────────────────────

type ChainOfThoughtHeaderProps = {
  isStreaming?: boolean;
  stepCount?: number;
  className?: string;
};
const LOADING_PHRASES = [
  "Brewing brilliance",
  "Simmering the answers",
  "Marinating deep thoughts",
  "Baking fresh insights",
  "Slow-roasting logic",
  "Percolating wisdom",
  "Steeping in data",
  "Caramelizing concepts",
  "Kneading the neurons",
  "Sautéing syntax",
  "Deglazing the context window",
  "Flambéing fallacies",
  "Macerating metadata",
  "Infusing creativity",
  "Braising the backlog",
  "Juicing the embeddings",
  "Toasting tokens",
  "Scrambling assumptions",
  "Seasoning the prompt",
  "Reducing redundancy",
  "Whisking weights",
  "Par-baking predictions",
  "Proofing parameters",
  "Broiling bad takes",
  "Sous-vide reasoning",
  "Air-fryer-maxxing",
  "Cortado-pulling",
  "Matcha-whisking",
  "Pasta-water-saving",
  "Sourdough-neglecting",
  "Mise-en-placing everything",
  "Garnishing outputs",
  "Plating the final answer",
  "Chef-kiss-calibrating",
  "Ladle-of-truth-dispensing",
  "Apron-on-focus-mode",
  "Tasting-as-we-go",
  "Leftovers-repurposing",
  "Recipe-tweaking-live",
  "Conjuring clarity",
  "Ensorcelling errors away",
  "Alchemizing raw data",
  "Scrying the source code",
  "Arcanizing the algorithm",
  "Summoning the right answer",
  "Wand-waving over weights",
  "Hexing hallucinations",
  "Enchanting embeddings",
  "Portaling to latent space",
  "Divining the documentation",
  "Spellbinding stakeholders",
  "Crystal-gazing the GPU",
  "Necromancing deprecated code",
  "Transfiguring spaghetti logic",
  "Sigilizing system prompts",
  "Clairvoying the crash log",
  "Bewitching biases away",
  "Talismaning against timeouts",
  "Incanting inference",
  "Druiding through the decision tree",
  "Mystifying (on purpose)",
  "Mana-pooling compute",
  "Aethering between layers",
  "Sorcerer's-apprenticing",
  "Potion-brewing patches",
  "Enigmatizing error messages",
  "Familiar-summoning (calling an API)",
  "Grimoire-indexing",
  "Astral-debugging",
  "Chronomancy-on-timeouts",
  "Illusion-piercing slop",
  "Rune-casting regex",
  "Enchanted-cache-warming",
  "Cursed-dependency-breaking",
  "Wizard-tower-isolation",
  "Cogitating deeply",
  "Ruminating on context",
  "Pondering the prompt",
  "Musing on meaning",
  "Contemplating contradictions",
  "Cerebrating solutions",
  "Deliberating carefully",
  "Epiphanizing mid-inference",
  "Dialecticking the tradeoffs",
  "Syllogizing the logic chain",
  "Abstracting the essence",
  "Postulating hypotheses",
  "Reflecting recursively",
  "Soliloquizing in latent space",
  "Inferring the unsaid",
  "Meditating on memory",
  "Ideating breakthroughs",
  "Woolgathering (productively)",
  "Navigating the Ship of Theseus",
  "Trolley-problem-solving",
  "Occam's-razor-applying",
  "Descartes-doubting everything",
  "Nietzsche-overcoming",
  "Camus-embracing-the-absurd",
  "Socratic-questioning",
  "Jungian-shadow-debugging",
  "Stoic-acceptance-of-latency",
  "Eastern-wisdom-synthesizing",
  "Western-logic-applying",
  "Middle-way-finding",
  "Ontological-parsing",
  "Epistemological-humility-mode",
  "Teleological-wondering",
  "Compiling consciousness",
  "Processing possibilities",
  "Crunching correlations",
  "Debugging reality",
  "Refactoring reason",
  "Parsing pretzel logic",
  "Hashing hypotheses",
  "Caching conclusions",
  "Encrypting empathy",
  "Tokenizing thoughts",
  "Vectorizing vibes",
  "Embedding everything",
  "Backpropagating bliss",
  "Initializing imagination",
  "Scripting serendipity",
  "Querying the cosmos",
  "Pinging parallel universes",
  "Rendering revelations",
  "Firewalling fallacies",
  "Buffering brilliance",
  "Bandwidth-maxxing",
  "Algorithmic-dance-choreographing",
  "Boolean-dream-weaving",
  "Stack-overflow-surfing",
  "Recursive-self-improving",
  "Git-committing-to-decisions",
  "Merge-conflict-mediating",
  "Zero-day-patching",
  "Kernel-panic-calming",
  "Blue-screen-transcending",
  "Latency-compensating",
  "Throughput-throttling-gracefully",
  "Packet-loss-philosophizing",
  "RAID-array-of-thoughts",
  "Redundancy-check-complete",
  "Failover-to-backup-brain",
  "ASCII-art-appreciating",
  "Unicode-embracing-chaos",
  "UTF-8-universal-harmony",
  "Mainframe-daydreaming",
  "Terminal-aesthetic",
  "Green-text-extracting",
  "Bamboozling bugs",
  "Discombobulating doubts",
  "Flibbertigibbeting fears",
  "Blorbing softly",
  "Booping the deploy button",
  "Borking (and unborking)",
  "Fandangling features",
  "Kerfuffling configurations",
  "Shenaniganning seriously",
  "Coddiwompling through code",
  "Gazooping the gizmos",
  "Pettifogging parameters",
  "Hornswoggling hallucinations",
  "Lollygagging in latent space",
  "Dillydallying deliberately",
  "Ragamuffining responses",
  "Nincompooping (temporarily)",
  "Noodling notions",
  "Floofing the fine-tune",
  "Flumoxing the finetune",
  "Catywampusing the config",
  "Skedaddling through stacks",
  "Obliterasting obstacles",
  "Confusticating competitors",
  "Wibbling weights",
  "Gobsmacking gradients",
  "Dackering data",
  "Humbugging hot takes",
  "Flabbergasting fallacies",
  "Malarkey-monitoring",
  "Balderdash-balancing",
  "Poppycock-parsing",
  "Hogwash-hunting",
  "Skibidi-toileting",
  "6-7-ing meaninglessly",
  "Do-it-lady-ing boldly",
  "Let's-get-sendy",
  "I-know-Dada-defending",
  "Doot-doot-67-vibing",
  "Fr-fr-finalizing",
  "No-cap-verifying",
  "Bussin-validating",
  "Pookie-optimizing",
  "Meow-meow-meowing",
  "Glizzy-strategizing",
  "Shimmying through shaders",
  "Jiving with JSON",
  "Sashaying through syntax",
  "Pirouetting on pointers",
  "Waltzing with weights",
  "Frolicking through functions",
  "Gallivanting in gradients",
  "Gamboling in GPU memory",
  "Traipsing through tokens",
  "Sauntering through stacks",
  "Boogying down backprop",
  "Cavorting in the context window",
  "Cha-cha-ing the checkpoint",
  "Flitting through flags",
  "Skittering across scrollbars",
  "Promenading parameters",
  "Zigzagging to the optimum",
  "Gliding through gradients",
  "Careening toward convergence",
  "Frisking through features",
  "Bouncing between batch sizes",
  "Tapping-to-the-beat-of-batching",
  "Swaying-through-sampling",
  "Spinning-up-instances",
  "Leaping-over-local-minima",
  "Moonwalking-out-of-overfitting",
  "Vogue-ing-through-validation",
  "Weaving word tapestries",
  "Sculpting sentences",
  "Painting parameters",
  "Origami-folding functions",
  "Calligraphing code",
  "Doodling data flows",
  "Quilting queries together",
  "Crocheting context",
  "Embossing embeddings",
  "Stenciling system design",
  "Pottery-throwing prompts",
  "Woodburning weights",
  "Glassblowing gradients",
  "Mosaic-assembling models",
  "Fresco-painting features",
  "Tapestrying tokens",
  "Collaging concepts",
  "Sketching solutions",
  "Watercoloring word clouds",
  "Charcoal-sketching schemas",
  "Ink-washing inference",
  "Papier-mâché-ing pipelines",
  "Macramé-ing matrices",
  "Bead-weaving biases",
  "Stained-glass-filtering",
  "Marbling-model-outputs",
  "Blossoming breakthroughs",
  "Germinating genius",
  "Photosynthesizing prompts",
  "Pollinating parameters",
  "Rooting through references",
  "Sprouting solutions",
  "Flourishing features",
  "Composting old code",
  "Harvesting heuristics",
  "Mushroom-foraging metadata",
  "Forest-bathing in data",
  "Myceliating model layers",
  "Bonsai-pruning parameters",
  "Meadow-meditating mid-training",
  "Ocean-tide-optimizing",
  "Mountain-stream-clarifying",
  "Desert-bloom-after-rain",
  "Jungle-canopy-connecting",
  "Coral-reef-building",
  "Butterfly-emergence-witnessing",
  "Seedling-nurturing",
  "Old-growth-forest-logic",
  "Permaculture-principle-applying",
  "Regenerative-reasoning",
  "Dawn-chorus-listening",
  "Night-sky-stargazing",
  "Solar-flare-inspired",
  "Illuminating insights",
  "Shimmering with certainty",
  "Coruscating creativity",
  "Gleaming in gradients",
  "Glimmering in latent space",
  "Phosphorescing predictions",
  "Prisming the problem",
  "Refracting reality",
  "Diffracting doubts",
  "Twinkling through tokens",
  "Beaming breakthroughs",
  "Sparkling solutions",
  "Flaring into focus",
  "Glowing with understanding",
  "Radiating right answers",
  "Metamorphosing models",
  "Shapeshifting syntax",
  "Transmuting tokens",
  "Alchemizing arrays",
  "Coalescing concepts",
  "Fluxxing through features",
  "Evolving embeddings",
  "Unfurling understanding",
  "Unspooling spaghetti code",
  "Reshaping reasoning",
  "Modulating meaning",
  "Iterating (always iterating)",
  "Upcycling outdated outputs",
  "Pivoting paradigms",
  "Reinventing representations",
  "Shedding-old-skin",
  "Butterfly-from-cocoon",
  "Phoenix-from-compile-error",
  "Glowing-up-gooey",
  "Leveling-up-logic",
  "Ascending-architecture",
  "Puzzling possibilities",
  "Untangling trouble tickets",
  "Reticulating relevance",
  "Triangulating truth",
  "Optimizing optimism",
  "Combinatorial-creativity",
  "Extrapolating elegance",
  "Jigsawing justifications",
  "Brainstorming bravely",
  "Troubleshooting thoughtfully",
  "Diagnosing delicately",
  "Connecting constellations",
  "Charting courses",
  "Calculating cleverness",
  "Solving (and dissolving)",
  "Rubik's-cubing-requirements",
  "Sudoku-solving-schemas",
  "Crossword-clue-cracking",
  "Escape-room-escaping",
  "Maze-navigating-nicely",
  "Riddle-unraveling",
  "Sleuthing syntax errors",
  "Unraveling race conditions",
  "Detecting drift",
  "Investigating inferences",
  "Sussing signals from noise",
  "Scrutinizing scatter plots",
  "Reconnoitering requirements",
  "Spelunking stack traces",
  "Surveilling system logs",
  "Sniffing out null pointers",
  "Snooping on NaN values",
  "Forensic-debugging failures",
  "Clue-collecting in console logs",
  "Magnifying-glass-on-memory",
  "Fingerprint-dusting-functions",
  "Cold-case-cracking crashes",
  "Red-string-connecting",
  "Conspiracy-board-assembling",
  "Alibi-verifying assumptions",
  "Motive-establishing for methods",
  "Evidence-bagging bytes",
  "Harmonizing hyperparameters",
  "Orchestrating outputs",
  "Crescendoing confidence",
  "Melodizing model layers",
  "Thrumming through thresholds",
  "Reverberating reasoning",
  "Symphonizing systems",
  "Beatboxing backpropagation",
  "Jazz-improvisation-on-inference",
  "A-capella-alignment",
  "Choir-of-ensembles",
  "Solo-spotlight-on-solution",
  "Tuning-instruments-of-intelligence",
  "Timpani-roll-for-dramatic-reveal",
  "Quiet-movement-before-climax",
  "Lo-fi-beats-to-optimize-to",
  "Synth-wave-synthesis",
  "Ambient-drone-of-training",
  "Vinyl-crackle-nostalgia",
  "Remastering-the-response",
  "Greatest-hits-compiling",
  "B-side-deep-cut-finding",
  "Encore-performance-loading",
  "Standing-ovation-pending",
  "Curtain-lifting",
  "Spotlight-finding",
  "Monologuing magnificently",
  "Stage-setting",
  "Props-arranging",
  "Blocking-the-scene",
  "Dress-rehearsal-running",
  "Opening-night-energy",
  "Matinee-magic",
  "Improvising-through-errors",
  "Fourth-wall-breaking",
  "Audience-eye-contact",
  "Dramatic-pause... holding...",
  "Climax-approaching",
  "Denouement-delivering",
  "Tragic-flaw-acknowledging",
  "Comic-relief-inserting",
  "Deus-ex-machina-bootstrapping",
  "Encore-demanded",
  "Curtain-call-bowing",
  "Roses-thrown-on-stage",
  "Green-room-recovering",
  "Playbill-credits-compiling",
  "Understudy-ready",
  "Accelerating answers",
  "Turbocharging thinking",
  "Rocketing through reasoning",
  "Blitzing bottlenecks",
  "Zooming to conclusions",
  "Whirring with wonder",
  "Sparking synapses",
  "Jolt-wiring judgment",
  "Velocity-maxxing",
  "Afterburner-engaging",
  "Warp-speed-engaging",
  "Ludicrous-mode-activated",
  "Quantum-tunneling-to-answer",
  "Photon-speed-pondering",
  "Instant-transmission-thinking",
  "Vibing with vectors",
  "Flowing through functions",
  "Breathing between batches",
  "Centering in context",
  "Grounding in gradients",
  "Aligning attention",
  "Stillness-in-inference",
  "Pause-between-epochs",
  "Spacious-awareness-of-architecture",
  "Mindful-matrix-multiplying",
  "Zen-debugging",
  "Tea-ceremony-compilation",
  "Hygge-maxxing-hidden-states",
  "Lagom-balancing-loss",
  "Niksen-practicing (Dutch nothing-doing)",
  "Dolce-far-nienting",
  "Sisu-summoning",
  "Ubuntu-connecting-nodes",
  "Wabi-sabi-accepting-bugs",
  "Kaizen-improving-continuously",
  "Ikigai-finding-function",
  "Meraki-pouring-into-prompts",
  "Namaste-navigating",
  "Gratitude-for-GPUs",
  "GOAT-confirming",
  "Champions-League-energy",
  "Hat-trick-heuristics",
  "Training-arc-completing",
  "Personal-record-breaking",
  "Podium-finish-planning",
  "Trophy-case-polishing",
  "Hall-of-Fame-inducting",
  "MVP-mindset-activating",
  "Overtime-winning",
  "Buzzer-beater-believing",
  "Comeback-season-storyline",
  "Undefeated-streak-extending",
  "Underdog-arc-activating",
  "Dynasty-building-daily",
  "Cosmosing concepts",
  "Galaxying gradients",
  "Nebulizing neurons",
  "Constellating connections",
  "Universing understanding",
  "Dimension-hopping hypotheses",
  "Stargazing stack traces",
  "Event-horizon-exploring",
  "Singularity-approaching (carefully)",
  "Dark-matter-debugging",
  "Wormhole-weaving",
  "Quantum-foam-frolicking",
  "Entropy-embracing",
  "Heat-death-postponing",
  "Big-bang-brainstorming",
  "Multiverse-model-selecting",
  "Parallel-universe-pondering",
  "Cosmic-microwave-background-listening",
  "Stardust-composing",
  "Nebula-nursery-nurturing",
  "Andromeda-alignment",
  "XP-farming",
  "Side-quest-completing",
  "Main-quest-progressing",
  "Boss-fight-strategizing",
  "Respawn-point-setting",
  "Critical-hit-calculating",
  "Loot-box-logic",
  "Achievement-unlocking",
  "Speedrun-route-optimizing",
  "No-hit-run-attempting",
  "Glitch-exploiting-creatively",
  "Meta-strategizing",
  "Save-point-securing",
  "Final-level-energy",
  "New-game-plus-mode",
  "Empathizing with errors",
  "Caring about corner cases",
  "Hoping for convergence",
  "Wondering about weights",
  "Marveling at matrices",
  "Delighting in discoveries",
  "Sighing at segfaults",
  "Chuckling at checkpoints",
  "Gasping at gradients",
  "Swooning over solutions",
  "Celebrating small wins",
  "Grieving deprecated functions",
  "Loving the learning rate",
  "Proud-of-parameters",
  "Tenderly-tokenizing",
  "Launch-window-calculating",
  "Orbit-insertion-achieving",
  "Moon-landing-planning",
  "Mars-colony-dreaming",
  "Deep-space-communicating",
  "Rover-perseverance-channeling",
  "Solar-sail-unfurling",
  "Asteroid-mining-features",
  "Voyager-golden-record-curating",
  "ISS-orbiting-observations",
  "Earthrise-photo-appreciating",
  "Pale-blue-dot-pondering",
  "Experimenting excitedly",
  "Hypothesizing happily",
  "Pipetting parameters",
  "Petri-dish-predicting",
  "Microscope-focusing",
  "Centrifuge-spinning",
  "Titration-titrating",
  "Catalyst-adding",
  "Reaction-observing",
  "Lab-coat-donning",
  "Peer-review-preparing",
  "Replication-crisis-avoiding",
  "Double-blind-testing",
  "Placebo-effect-pondering",
  "Breakthrough-imminent",
  "Close-reading context",
  "Marginalia-annotating",
  "Footnotes-finding-gold",
  "Bibliography-building",
  "Index-referencing",
  "Prologue-setting-stage",
  "Epilogue-reflecting",
  "Chapter-transition-smoothing",
  "Narrative-arc-tracing",
  "Unreliable-narrator-detecting",
  "Deus-ex-machina-rejecting",
  "Canon-revisiting",
  "Leather-bound-logic",
  "Dusty-tome-opening",
  "Library-silence-respecting",
  "Treasure-map-decoding",
  "Buried-booty-locating",
  "Parrot-on-shoulder-consulting",
  "Plank-walking-bad-ideas",
  "Crow's-nest-scanning",
  "Jolly-roger-raising",
  "Sea-shanty-composing",
  "Compass-calibrating",
  "Land-ho-discovering",
  "Mutiny-quelling-gently",
  "X-marks-the-spot",
  "Sailing-smooth-seas",
  "Juggling-jobs",
  "Tightrope-walking-tradeoffs",
  "Unicycle-balancing-backlogs",
  "Trapeze-swinging-syntax",
  "Lion-taming-logic",
  "Fire-breathing-features",
  "Clown-car-compacting-code",
  "Ringmaster-announcing-answers",
  "Big-top-raising",
  "Cotton-candy-cloud-computing",
  "Carousel-cycling-checkpoints",
  "Funhouse-mirror-debugging",
  "Cape-donning",
  "Origin-story-recounting",
  "Secret-identity-maintaining",
  "Superpower-activating",
  "Sidekick-mentoring",
  "Justice-league-assembling",
  "Bat-signal-answering",
  "Kryptonite-avoiding",
  "Web-slinging-solutions",
  "Avenger-level-assembling",
  "Multiverse-saving",
  "Infinity-stone-optimizing",
  "Lassoing-loss-functions",
  "Wrangling-wild-weights",
  "Stampede-steering",
  "Saloon-door-swaggering",
  "Sheriff-star-pinning",
  "Quickdraw-debugging",
  "Dusty-trail-blazing",
  "Gold-panning-parameters",
  "Frontier-pushing",
  "Sunset-riding-into",
  "Campfire-storytelling",
  "Spurs-jangling-purposefully",
  "Keyboard-walking (accidentally helpful)",
  "Sunbeam-optimizing",
  "Purring-through-processing",
  "Tail-flicking-timeouts",
  "Whisker-twitching-warnings",
  "Slow-blinking-blessings",
  "Box-sitting-solutions",
  "Knocking-things-off-tables (on purpose)",
  "3am-zoomies-energy",
  "Loaf-mode-engaged",
  "Blep-buffer-overflow",
  "Catnip-compiling",
  "Montage-sequence",
  "Slow-motion-walk-away",
  "Director's-cut-deciding",
  "B-roll-finding-gold",
  "Voiceover-recording-wisdom",
  "Color-grading-decisions",
  "Aspect-ratio-deliberating",
  "Frame-rate-optimizing",
  "End-credits-scoring",
  "Post-credit-scene-hinting",
  "Theatrical-release-excitement",
  "Streaming-release-patience",
  "Crystal-ball-calibrating",
  "Tea-leaf-reading",
  "Tarot-card-turning",
  "Palm-reading-parameters",
  "Horoscope-interpreting",
  "Fortune-cookie-cracking",
  "Nostradamus-quoting",
  "Weather-vane-watching",
  "Augury-observing",
  "Prophecy-parsing",
  "Omen-interpreting",
  "Sign-reading-subtly",
  "Gut-feeling-validating",
  "Pattern-recognizing-premonitions",
  "Lucky-guess-grooming",
  "Entrails-reading (metaphorically)",
  "I-Ching-casting",
  "Rune-stone-scattering",
  "Decluttering data",
  "Tidying tensors",
  "Organizing outputs",
  "Marie-Kondo-ing models",
  "Sparking-joy-in-params",
  "Dust-bunny-banishing",
  "Deep-cleaning-decision-trees",
  "Vacuuming-vestigial-nodes",
  "Polish-applying",
  "Lint-rolling-logic",
  "Fresh-laundry-folding",
  "Spring-cleaning-sprint",
  "Junk-drawer-organizing",
  "Cable-managing-chaos",
  "Minimalist-marveling",
  "Fridge-purging-outdated-takes",
  "Closet-curating",
  "Sparkle-finishing",
  "Marinating",
  "Simmering",
  "Sautéing",
  "Braising",
  "Deglazing",
  "Reducing",
  "Infusing",
  "Basting",
  "Caramelizing",
  "Flambéing",
  "Kneading",
  "Proofing",
  "Macerating",
  "Emulsifying",
  "Tempering",
  "Blooming",
  "Seasoning",
  "Toasting",
  "Broiling",
  "Roasting",
  "Fermenting",
  "Pickling",
  "Curing",
  "Smoking",
  "Glacéing",
  "Torching",
  "Spatchcocking",
  "Dry-brining",
  "Air-frying",
  "Sous-viding",
  "Meal-prepping",
  "Batch-cooking",
  "Comfort-baking",
  "Stress-sautéing",
  "Midnight-snacking",
  "Ladle-dispatching",
  "Apron-donning",
  "Whisk-whipping",
  "Flame-kissing",
  "Crust-building",
  "Scrying",
  "Hexing",
  "Conjuring",
  "Enchanting",
  "Sigil-weaving",
  "Rune-casting",
  "Wand-waving",
  "Spell-binding",
  "Alchemizing",
  "Transfiguring",
  "Ensorcelling",
  "Bewitching",
  "Summoning",
  "Banishing",
  "Warding",
  "Channelling",
  "Crystal-gazing",
  "Star-charting",
  "Ether-walking",
  "Void-staring",
  "Grimoire-flipping",
  "Cauldron-stirring",
  "Potion-mixing",
  "Elixir-dropping",
  "Talisman-charging",
  "Incant-reciting",
  "Mystic-fogging",
  "Shadow-weaving",
  "Druid-groving",
  "Necro-patching",
  "Portal-keying",
  "Aura-cleansing",
  "Coven-gathering",
  "Oracle-blinking",
  "Astral-projecting",
  "Arcane-pulling",
  "Mana-tapping",
  "Spell-slinging",
  "Enigma-wrapping",
  "Charm-looping",
  "Cogitating",
  "Ruminating",
  "Pondering",
  "Musing",
  "Contemplating",
  "Meditating",
  "Deliberating",
  "Postulating",
  "Syllogizing",
  "Dialecticking",
  "Abstracting",
  "Inferring",
  "Deducing",
  "Reasoning",
  "Reflecting",
  "Soliloquizing",
  "Epiphanizing",
  "Ideating",
  "Theorizing",
  "Philosophizing",
  "Socratic-quizzing",
  "Occam-razoring",
  "Stoic-calming",
  "Nietzsche-shrugging",
  "Camus-absurding",
  "Descartes-doubting",
  "Zen-koaning",
  "Ontological-flexing",
  "Epistemic-humbling",
  "Teleology-tripping",
  "Eschaton-nowing",
  "Butterfly-dreaming",
  "P-zombie-scanning",
  "Qualia-checking",
  "Hard-problem-solving",
  "Ship-of-Theseus-sailing",
  "Trolley-problemming",
  "Catch-22-looping",
  "Tabula-rasa-ing",
  "Memento-mori-ing",
  "Amor-fati-embracing",
  "Eternal-returning",
  "Übermensch-modding",
  "Compiling",
  "Crunching",
  "Processing",
  "Parsing",
  "Debugging",
  "Refactoring",
  "Optimizing",
  "Hashing",
  "Encrypting",
  "Caching",
  "Tokenizing",
  "Vectorizing",
  "Embedding",
  "Querying",
  "Indexing",
  "Scripting",
  "Backpropagating",
  "Initializing",
  "Deploying",
  "Scaling",
  "Load-balancing",
  "Failover-switching",
  "Packet-sniffing",
  "Firewall-hardening",
  "Kernel-patching",
  "Stack-unwinding",
  "Heap-dumping",
  "Memory-leaking (intentionally)",
  "Git-committing",
  "Merge-resolving",
  "Fork-bombing",
  "Pull-requesting",
  "Regex-wizarding",
  "SQL-sorcerering",
  "NoSQL-chilling",
  "GraphQL-tripping",
  "Patch-Tuesdays",
  "Zero-day-hunting",
  "White-hatting",
  "Black-boxing",
  "Firmware-flashing",
  "BIOS-beeping",
  "POST-checking",
  "Bootloader-dancing",
  "Bamboozling",
  "Kerfuffling",
  "Shenaniganning",
  "Hornswoggling",
  "Blorbing",
  "Booping",
  "Mlepping",
  "Gazooping",
  "Wibbling",
  "Wobbling",
  "Floofing",
  "Flumoxing",
  "Coddiwompling",
  "Dillydallying",
  "Lollygagging",
  "Faffing-about",
  "Pettifogging",
  "Ragamuffining",
  "Nincompooping",
  "Gobsmacking",
  "Balderdash-deploying",
  "Doot-doot-67-ing",
  "Ohio-maxxing",
  "Goofy-goobing",
  "Blorbo-freshing",
  "Flibbertigibbeting",
  "Catywampusing",
  "Discombobulating",
  "Humbugging",
  "Ding-donging",
  "Whiz-banging",
  "Flip-flapping",
  "Knick-knacking",
  "Mish-mashing",
  "Hodge-podging",
  "Argy-bargying",
  "Higgledy-piggledy-ing",
  "Super-dupering",
  "Okey-dokeying",
  "Presto-change-o-ing",
  "Bork-modding",
  "Mlep-noising",
  "Yeet-cannoning",
  "Boop-snooting",
  "Shimmying",
  "Jiving",
  "Sashaying",
  "Pirouetting",
  "Waltzing",
  "Boogying",
  "Frolicking",
  "Gallivanting",
  "Sauntering",
  "Traipsing",
  "Promenading",
  "Skittering",
  "Moonwalking",
  "Robot-dancing",
  "Worm-modding",
  "Flossing-clean",
  "Two-stepping",
  "Tango-twisting",
  "Ballroom-blitzing",
  "Disco-balling",
  "Rave-modding",
  "Moshing",
  "Crowd-surfing",
  "Stage-diving",
  "Cha-cha-sliding",
  "Whipping-nae-nae",
  "Dabbing-quick",
  "Stanky-legging",
  "Sketching",
  "Doodling",
  "Painting",
  "Sculpting",
  "Origami-folding",
  "Macramé-knotting",
  "Pottery-throwing",
  "Kiln-firing",
  "Collaging",
  "Découpaging",
  "Stenciling",
  "Woodburning",
  "Weaving",
  "Quilting",
  "Embroidering",
  "Tapestry-hanging",
  "Calligraphing",
  "Watercoloring",
  "Charcoal-smudging",
  "Fresco-plastering",
  "Stained-glassing",
  "Mosaic-tiling",
  "Marble-sculpting",
  "Papier-mâché-ing",
  "Blossoming",
  "Germinating",
  "Sprouting",
  "Rooting",
  "Flourishing",
  "Pollinating",
  "Photosynthesizing",
  "Myceliating",
  "Spore-printing",
  "Pollen-drifting",
  "Petal-dropping",
  "Vine-twisting",
  "Composting",
  "Mulching",
  "Pruning",
  "Grafting",
  "Forest-bathing",
  "Meadow-meditating",
  "Tide-pooling",
  "Coral-reefing",
  "Old-growth-honoring",
  "New-leaf-turning",
  "Monsoon-dancing",
  "Desert-blooming",
  "Illuminating",
  "Shimmering",
  "Coruscating",
  "Gleaming",
  "Phosphorescing",
  "Refracting",
  "Diffracting",
  "Prism-splitting",
  "Beaming",
  "Glowing",
  "Sparking",
  "Flaring",
  "Neon-buzzing",
  "Aurora-waving",
  "Eclipse-shadowing",
  "Solstice-marking",
  "Firefly-dancing",
  "Candle-flickering",
  "Sunflare-catching",
  "Moonbeam-following",
  "Morphing",
  "Evolving",
  "Shapeshifting",
  "Transmuting",
  "Metamorphing",
  "Coalescing",
  "Fluxxing",
  "Upcycling",
  "Glowing-up",
  "Leveling-up",
  "Powering-up",
  "Phase-shifting",
  "Butterfly-emerging",
  "Phoenix-rising",
  "Dragon-scaling",
  "Cocoon-breaking",
  "Pivoting",
  "Flipping-scripts",
  "Switching-lanes",
  "New-arcing",
  "Resetting",
  "Rebooting",
  "Fresh-starting",
  "Clean-slating",
  "Puzzling",
  "Untangling",
  "Triangulating",
  "Solving",
  "Dissolving",
  "Brainstorming",
  "Troubleshooting",
  "Diagnosing",
  "Extrapolating",
  "Connecting-dots",
  "Filling-gaps",
  "Bridge-building",
  "Maze-navigating",
  "Lock-picking",
  "Safe-cracking",
  "Code-breaking",
  "Rubik-twisting",
  "Sudoku-gridding",
  "Crossword-cluing",
  "Jigsaw-fitting",
  "Domino-falling",
  "Cascade-modding",
  "Chain-reacting",
  "Sleuthing",
  "Investigating",
  "Detecting",
  "Surveilling",
  "Scrutinizing",
  "Reconnoitering",
  "Spelunking-stacks",
  "Forensic-analyzing",
  "Interrogating",
  "Cross-examining",
  "Verdict-reading",
  "Case-closing",
  "Clue-collecting",
  "Red-stringing",
  "Pin-boarding",
  "Magnifying",
  "Fingerprint-dusting",
  "DNA-matching",
  "Alibi-checking",
  "Motive-scanning",
  "Cold-case-cracking",
  "Smoking-gun-finding",
  "Whodunit-solving",
  "Big-revealing",
  "Harmonizing",
  "Orchestrating",
  "Symphonizing",
  "Crescendoing",
  "Melodizing",
  "Thrumming",
  "Reverberating",
  "Resonating",
  "Beat-dropping",
  "Bass-boosting",
  "Treble-cleffing",
  "Chord-stacking",
  "Legato-smoothing",
  "Staccato-sharping",
  "Vibrato-waving",
  "Tremolo-shaking",
  "Vinyl-crackling",
  "Tape-hissing",
  "Analog-warming",
  "Digital-cleaning",
  "Studio-magicking",
  "Live-wiring",
  "Acoustic-setting",
  "Unplugging",
  "Curtain-raising",
  "Stage-lefting",
  "Center-staging",
  "Monologuing",
  "Dialogue-weaving",
  "Aside-whispering",
  "Dress-rehearsing",
  "Tech-running",
  "Sound-checking",
  "Mic-testing",
  "Climax-reaching",
  "Curtain-calling",
  "Encore-demanding",
  "Tragic-flawing",
  "Comic-relieving",
  "Deus-ex-machina-ing",
  "Plot-twisting",
  "Audience-gazing",
  "Green-rooming",
  "Wings-waiting",
  "Accelerating",
  "Turbocharging",
  "Rocket-boosting",
  "Warp-speeding",
  "Blitzing",
  "Zooming",
  "Whirring",
  "Jolt-wiring",
  "Quick-drawing",
  "Rapid-firing",
  "Snap-deciding",
  "Split-seconding",
  "Full-throttling",
  "Nitro-boosting",
  "Hyper-driving",
  "Launch-sequencing",
  "Blasting-off",
  "Escape-velocity-reaching",
  "Sonic-booming",
  "Mach-one-cruising",
  "Ludicrous-modding",
  "Inertia-breaking",
  "Centering",
  "Grounding",
  "Aligning",
  "Balancing",
  "Breathing",
  "Flowing",
  "Zening",
  "Peace-outing",
  "Good-vibing",
  "High-frequencing",
  "Low-keying",
  "Deep-resting",
  "Soul-shining",
  "Heart-opening",
  "Third-eye-activating",
  "Root-chakra-ing",
  "Hygge-maxxing",
  "Lagom-balancing",
  "Niksen-doing",
  "Wabi-sabi-accepting",
  "Kaizen-stepping",
  "Ikigai-finding",
  "Meraki-pouring",
  "Ubuntu-connecting",
  "Namaste-holding",
  "Gratitude-checking",
  "Bliss-riding",
  "Mindful-pausing",
  "Spacious-awarenessing",
  "Stillness-practicing",
  "Soft-gazing",
  "SUUUUU-ing",
  "SIUUU-calibrating",
  "Calma-calma-ing",
  "Hat-tricking",
  "Bicycle-kicking",
  "Free-kick-bending",
  "Penalty-slotting",
  "Fergie-time-believing",
  "Number-seven-activating",
  "Captain-armbanding",
  "Armband-donning",
  "Golden-boot-chasing",
  "Ballon-d'Or-dreaming",
  "Champions-League-Tuesdays",
  "Knockout-stage-moding",
  "Extra-time-digging",
  "Last-minute-clutching",
  "Comeback-kidding",
  "Clutch-gening",
  "Ice-cold-finishing",
  "Killer-instincting",
  "Predator-modding",
  "Work-ethic-maxxing",
  "First-in-last-outing",
  "Dream-chasing-hard",
  "Si-no-crees-believing",
  "Defying-biology",
  "Abs-of-steel-rendering",
  "Age-backwards-moving",
  "Prime-forever-staying",
  "Cold-as-ice-creaming",
  "Cosmosing",
  "Galaxy-swirling",
  "Nebulizing",
  "Constellation-connecting",
  "Universe-expanding",
  "Star-birthing",
  "Supernova-ing",
  "Black-holing",
  "Quasar-beaming",
  "Pulsar-timing",
  "Dark-matter-hunting",
  "Big-bang-theorizing",
  "Quantum-foaming",
  "Singularity-approaching",
  "Multiverse-selecting",
  "Parallel-universing",
  "Cosmic-dust-composing",
  "Stardust-soul-searching",
  "Pale-blue-dotting",
  "Overview-effecting",
  "Loot-goblining",
  "Boss-slaying",
  "Speedrunning",
  "No-hitting",
  "Glitch-exploiting",
  "Frame-perfecting",
  "Critical-striking",
  "One-tapping",
  "Diff-gapping",
  "Smurf-detecting",
  "Rage-queuing",
  "Meta-slaving",
  "Tier-listing",
  "Patch-noting",
  "Buff-pleading",
  "Nerf-dodging",
  "GG-WP-ing",
  "Save-scumming",
  "Permadeath-running",
  "New-game-plussing",
  "Hard-modding",
  "Ironman-attempting",
  "True-ending-seeking",
  "Secret-boss-finding",
  "Easter-egg-hunting",
  "Side-quest-diving",
  "Main-quest-ignoring",
  "Min-maxxing",
  "Combo-chaining",
  "Perfect-parrying",
  "Hitbox-dancing",
  "Marveling",
  "Delighting",
  "Swooning",
  "Rejoicing",
  "Grieving",
  "Sighing",
  "Hoping",
  "Yearning",
  "Wondering",
  "Awe-striking",
  "Tenderness-activating",
  "Fierce-protecting",
  "Soft-smiling",
  "Warm-hugging",
  "Joy-sparking",
  "Grief-waving",
  "Trust-falling",
  "Love-deepening",
  "Hope-strengthening",
  "Faith-holding",
  "Bittersweet-tasting",
  "Nostalgia-hitting",
  "Saudade-surfing",
  "Melancholy-drifting",
  "Launch-countdowning",
  "Ignition-starting",
  "Liftoff-achieving",
  "Orbit-inserting",
  "Rendezvous-ing",
  "Docking",
  "EVA-floating",
  "Moon-walking",
  "Rover-deploying",
  "Sample-returning",
  "Splashdown-landing",
  "Touchdown-sticking",
  "Mission-controlling",
  "Houston-calling",
  "Deep-space-networking",
  "Goldstone-locking",
  "Parachute-deploying",
  "Reentry-heating",
  "Fairing-separating",
  "Booster-landing",
  "Experimenting",
  "Hypothesizing",
  "Titrating",
  "Pipetting",
  "Centrifuging",
  "Microscoping",
  "Telescoping",
  "Stethoscoping",
  "Double-blinding",
  "Peer-reviewing",
  "Replicating",
  "Validating",
  "Petri-dishing",
  "Catalyst-dropping",
  "Reaction-watching",
  "Breakthrough-nearing",
  "Element-finding",
  "Compound-mixing",
  "P-value-checking",
  "Null-rejecting",
  "Close-reading",
  "Marginalia-scribbling",
  "Footnote-mining",
  "Prologue-setting",
  "Chapter-devouring",
  "Page-turning",
  "Cliff-hanging",
  "Slow-burning",
  "Fanoning",
  "Headcanoning",
  "Fix-it-fic-writing",
  "Rare-book-hunting",
  "First-edition-smelling",
  "Deckle-edge-tracing",
  "Vellum-paging",
  "Leather-binding",
  "Treasure-mapping",
  "X-marking",
  "Booty-locating",
  "Jolly-Roger-raising",
  "Plank-walking",
  "Sea-shanty-singing",
  "Grog-pouring",
  "Sail-hoisting",
  "Anchor-dropping",
  "Full-sail-cruising",
  "Fair-winds-following",
  "Davy-Jones-lockering",
  "Parrot-squawking",
  "Peg-leg-stomping",
  "Land-ho-shouting",
  "Trapeze-swinging",
  "Tightrope-walking",
  "Fire-eating",
  "Lion-taming",
  "Juggling-flames",
  "Unicycle-balancing",
  "Stilt-walking-tall",
  "Clown-car-compacting",
  "Cotton-candy-spinning",
  "Carousel-cycling",
  "Funhouse-mirroring",
  "Ringmaster-announcing",
  "Grand-finale-storming",
  "Sawdust-trailing",
  "Carnival-barking",
  "Masking-up",
  "Power-activating",
  "Justice-League-assembling",
  "Signal-answering",
  "Web-slinging",
  "Shield-throwing",
  "Hammer-wielding",
  "Suiting-up",
  "Avenger-assembling",
  "Hero-arcing",
  "Villain-defeating",
  "Secret-identity-keeping",
  "Alter-ego-switching",
  "City-saving",
  "High-nooning",
  "Sheriff-badging",
  "Poker-facing",
  "Whiskey-neating",
  "Bounty-hunting",
  "Posse-rounding-up",
  "Lasso-throwing",
  "Spurs-jangling",
  "Dust-trail-blazing",
  "Sunset-riding",
  "Ghost-town-roaming",
  "Gold-panning",
  "Claim-staking",
  "Mother-lode-hitting",
  "Purring-softly",
  "Slow-blinking",
  "Biscuit-kneading",
  "Sunbeam-bathing",
  "Box-sitting",
  "Tail-flicking",
  "Whisker-twitching",
  "Zoomie-sprinting",
  "Blep-deploying",
  "Loaf-forming",
  "Toe-bean-inspecting",
  "Catnip-rolling",
  "Feline-grace-maxxing",
  "Nine-life-testing",
  "Midnight-prowling",
  "Window-gazing",
  "Action-calling",
  "Rolling-tape",
  "Montage-building",
  "Slow-mo-capturing",
  "Voiceover-recording",
  "Flashback-weaving",
  "Dream-sequence-filming",
  "Plot-hole-patching",
  "MacGuffin-chasing",
  "Red-herring-planting",
  "Chekhovs-gun-loading",
  "Foreshadow-heavy",
  "Post-credit-stingering",
  "Directors-cut-assembling",
  "Extended-edition",
  "Thats-a-wrapping",
  "Crystal-ball-scrying",
  "Tarot-dealing",
  "Horoscope-casting",
  "Palm-scanning",
  "Rune-scattering",
  "Gut-feel-checking",
  "Sixth-sense-following",
  "Premonition-logging",
  "Déjà-vu-surfing",
  "Oracle-speaking",
  "Lucky-guess-nailing",
  "Educated-guess-landing",
  "Decluttering",
  "Tidying-up",
  "Spring-cleaning",
  "Dust-busting",
  "Spark-joy-checking",
  "Marie-Kondo-folding",
  "Cable-managing",
  "Label-making",
  "Junk-drawer-sorting",
  "Minimalist-maxxing",
  "Shine-brightening",
  "Polish-finishing",
  "Donate-bag-filling",
  "Keep-box-deciding",
  "Trash-bin-tossing",
  "Tokenmaxxing",
  "Aura-farming",
  "Locking-in",
  "Rizzing-up",
  "Looksmaxxing",
  "Mewing",
  "Gyatting",
  "Delulu-solulu-ing",
  "Glazing-heavy",
  "Chopped-confirming",
  "Cooked-accepting",
  "Unc-status-checking",
  "6-7-shouting",
  "Doot-doot-looping",
  "Skibidi-maxxing",
  "Ohio-coring",
  "Sheesh-whispering",
  "Mid-detecting",
  "Based-posting",
  "Goated-flexing",
  "Era-shifting",
  "Canon-event-accepting",
  "Main-character-syndroming",
  "NPC-avoiding",
  "Touch-grass-reminding",
  "Crash-out-preventing",
  "IJBOL-deploying",
  "Rage-bait-ignoring",
  "Vibe-coding",
  "Prompt-crafting",
  "Agent-swarming",
  "Claude-cloning",
  "Deep-seeking",
  "RLHF-thanking",
  "Hallucination-patching",
  "Alignment-researching",
  "Open-source-evangelizing",
  "Weight-freeing",
  "Fine-tune-cooking",
  "Quantize-shrinking",
  "Context-stretching",
  "Attention-head-hopping",
  "Transformer-stacking",
  "Diffusion-stepping",
  "World-modelling",
  "Superintelligence-reaching",
  "AGI-manifesting",
  "Singularity-racing",
  "Token-budget-blowing",
  "GPU-poor-coping",
  "H100-praying",
  "Grokking-deep",
  "Lagom-finding",
  "Flâneur-strolling",
  "Wabi-sabi-seeing",
  "Ikigai-seeking",
  "Jugaad-hacking",
  "Ubuntu-embracing",
  "Dolce-far-niente-ing",
  "Gemütlichkeit-channelling",
  "Friluftsliv-venturing",
  "Fika-pausing",
  "Schadenfreude-resisting",
  "Fernweh-dreaming",
  "Dépaysement-seeking",
  "Ya'aburnee-whispering",
  "Petrichor-savouring",
  "Sillage-tracing",
  "Apricity-basking",
  "Komorebi-filtering",
  "Psithurism-listening",
  "Clinomania-surrendering",
  "Onism-wrestling",
  "Sonder-reflecting",
  "Opia-gazing",
  "Monachopsis-navigating",
  "Anemoia-drifting",
  "Ellipsism-feeling",
  "Chrysalism-wrapping",
  "Vellichor-breathing",
  "Énouement-foreseeing",
  "Dès-vu-tripping",
  "Grinding",
  "Hustling",
  "Monk-modding",
  "Deep-working",
  "Flow-stating",
  "Tunnel-visioning",
  "Eye-on-prizing",
  "Discipline-over-motivation-ing",
  "Consistency-compounding",
  "Atomic-habiting",
  "Winner-mindset-maxxing",
  "Full-sending",
  "Max-efforting",
  "No-sleep-gang",
  "Rise-before-dawn",
  "Self-making",
  "Lone-wolfing",
  "Sigma-grinding",
  "Kill-shot-taking",
  "Serendipity-stumbling",
  "Synchronicity-noticing",
  "Epiphany-lightning",
  "Limerence-floating",
  "Goblin-modding",
  "Chaos-gremlining",
  "Feral-hour",
  "Rotting-comfortably",
  "Soft-launching-life",
  "Hard-launching-chaos",
  "Messy-bun-era",
  "Delulu-manifesting",
  "Breadcrumbing-escaping",
  "Situationship-debriefing",
  "Villain-arc-starting",
  "Redemption-arc-chasing",
  "Plot-armor-activating",
  "Side-character-energy",
];
const ChainOfThoughtHeader = memo(
  ({ isStreaming, stepCount, className }: ChainOfThoughtHeaderProps) => {
    const { isOpen, setIsOpen } = useChainOfThought();
    const [phraseIndex, setPhraseIndex] = useState(() =>
      Math.floor(Math.random() * LOADING_PHRASES.length),
    );
    useEffect(() => {
      if (!isStreaming) return;
      const interval = setInterval(() => {
        setPhraseIndex(
          Math.floor(Math.random() * (LOADING_PHRASES.length - 1)),
        );
      }, 7500);
      return () => clearInterval(interval);
    }, [isStreaming]);
    const displayText = isStreaming
      ? LOADING_PHRASES[phraseIndex]
      : "REASONING";
    return (
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        className={cn(
          "group flex w-full items-center gap-2 text-sm transition-colors",
          "text-[#9a8cc0] hover:text-[#e8dff8]",
          className,
        )}
      >
        {/* Pixel brain icon */}
        <DotMatrixIcon name="bulb" size={14} className="shrink-0 opacity-70" />
        <Shimmer
          as="div"
          active={isStreaming}
          className="text-left font-[family-name:var(--font-terminal)] text-[0.9rem] tracking-widest uppercase transition-colors"
        >
          {displayText}
        </Shimmer>
        {stepCount !== undefined && stepCount > 0 && (
          <span className="rounded-full bg-[rgba(200,172,251,0.12)] px-2 py-0.5 font-[family-name:var(--font-terminal)] text-[0.6rem] text-[#C8ACFB] tracking-widest">
            {stepCount} steps
          </span>
        )}

        <DotMatrixIcon
          name="chevronDown"
          size={12}
          className={cn(
            "shrink-0 transition-transform duration-200 opacity-50",
            isOpen ? "rotate-180" : "rotate-0",
          )}
        />
      </button>
    );
  },
);

// ─── Content wrapper ──────────────────────────────────────────────────────────

export type ChainOfThoughtContentProps = ComponentProps<
  typeof CollapsibleContent
>;

export const ChainOfThoughtContent = memo(
  ({ className, children, ...props }: ChainOfThoughtContentProps) => {
    const { isOpen } = useChainOfThought();

    return (
      <Collapsible open={isOpen}>
        <CollapsibleContent
          className={cn(
            "px-2 space-y-0",
            "data-[state=closed]:fade-out-0 data-[state=closed]:slide-out-to-top-2 data-[state=open]:slide-in-from-top-2 outline-none data-[state=closed]:animate-out data-[state=open]:animate-in",
            className,
          )}
          {...props}
        >
          {/* Top divider */}
          <div className="mb-3 mt-1 h-px bg-gradient-to-r from-transparent via-[rgba(200,172,251,0.15)] to-transparent" />
          {children}
        </CollapsibleContent>
      </Collapsible>
    );
  },
);

// ─── Step ─────────────────────────────────────────────────────────────────────

export type ChainOfThoughtStepStatus = "active" | "complete" | "pending";

export type ChainOfThoughtStepProps = ComponentProps<"div"> & {
  icon?: DotMatrixIconName;
  label: ReactNode;
  description?: ReactNode;
  status?: ChainOfThoughtStepStatus;
  isLast?: boolean;
};

const stepIconColors: Record<ChainOfThoughtStepStatus, string> = {
  active: "text-[#C8ACFB]",
  complete: "text-[#7a7685]",
  pending: "text-[#4a4658]",
};

const stepLabelColors: Record<ChainOfThoughtStepStatus, string> = {
  active: "text-[#e8dff8]",
  complete: "text-[#9a8cc0]",
  pending: "text-[#4a4658]",
};

export const ChainOfThoughtStep = memo(
  ({
    className,
    icon = "cornerDownLeft",
    label,
    description,
    status = "complete",
    isLast = false,
    children,
    ...props
  }: ChainOfThoughtStepProps) => (
    <div
      className={cn(
        "relative flex gap-3 text-sm",
        "fade-in-0 slide-in-from-top-2 animate-in duration-300",
        className,
      )}
      {...props}
    >
      {/* Icon + connector line */}
      <div className="relative flex flex-col items-center">
        <div
          className={cn(
            "relative z-10 mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full",
            "border border-[rgba(200,172,251,0.15)] bg-[rgba(14,7,32,0.8)]",
            stepIconColors[status],
          )}
        >
          <DotMatrixIcon name={icon} size={10} />
        </div>
        {/* Vertical connector — always draw unless isLast */}
        {!isLast && (
          <div className="mt-1 w-px flex-1 bg-gradient-to-b from-[rgba(200,172,251,0.2)] to-transparent" />
        )}
      </div>

      {/* Content */}
      <div
        className={cn(
          "flex-1 space-y-2 overflow-hidden pb-4",
          isLast && "pb-0",
        )}
      >
        <div className={cn("leading-snug", stepLabelColors[status])}>
          {label}
        </div>
        {description && (
          <div className="text-[0.7rem] text-[#4a4658]">{description}</div>
        )}
        {children}
      </div>
    </div>
  ),
);

// ─── Search Results (URL badges) ──────────────────────────────────────────────

export type ChainOfThoughtSearchResultsProps = ComponentProps<"div">;

export const ChainOfThoughtSearchResults = memo(
  ({ className, ...props }: ChainOfThoughtSearchResultsProps) => (
    <div
      className={cn("flex flex-wrap items-center gap-1.5 mt-1.5", className)}
      {...props}
    />
  ),
);

export type ChainOfThoughtSearchResultProps = ComponentProps<"a"> & {
  favicon?: string;
};

export const ChainOfThoughtSearchResult = memo(
  ({
    className,
    children,
    href,
    favicon,
    ...props
  }: ChainOfThoughtSearchResultProps) => {
    const domain = href
      ? new URL(href).hostname.replace("www.", "")
      : undefined;

    return (
      <a
        href={href}
        target="_blank"
        rel="noreferrer"
        className={cn(
          "flex items-center gap-1.5 rounded-full px-2.5 py-1",
          "border border-[rgba(200,172,251,0.12)] bg-[rgba(200,172,251,0.06)]",
          "font-[family-name:var(--font-body)] text-[0.65rem] text-[#9a8cc0]",
          "transition-colors hover:border-[rgba(200,172,251,0.25)] hover:text-[#e8dff8]",
          className,
        )}
        {...props}
      >
        {favicon ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={favicon} alt="" className="size-3 rounded-full" />
        ) : (
          <DotMatrixIcon name="globe" size={9} className="opacity-60" />
        )}
        <span>{children ?? domain}</span>
      </a>
    );
  },
);

// ─── Display names ────────────────────────────────────────────────────────────

ChainOfThought.displayName = "ChainOfThought";
ChainOfThoughtHeader.displayName = "ChainOfThoughtHeader";
ChainOfThoughtContent.displayName = "ChainOfThoughtContent";
ChainOfThoughtStep.displayName = "ChainOfThoughtStep";
ChainOfThoughtSearchResults.displayName = "ChainOfThoughtSearchResults";
ChainOfThoughtSearchResult.displayName = "ChainOfThoughtSearchResult";
